(eval-when (:compile-toplevel)
  (print '(:compile :a))
  (finish-output))
(eval-when (:load-toplevel)
  (print '(:load :a))
  (finish-output))
(eval-when (:execute)
  (print '(:execute :a))
  (finish-output))
