(eval-when (:compile-toplevel)
  (print '(:compile :c))
  (finish-output))
(eval-when (:load-toplevel)
  (print '(:load :c))
  (finish-output))
(eval-when (:execute)
  (print '(:execute :c))
  (finish-output))
