(eval-when (:compile-toplevel)
  (print '(:compile :d))
  (finish-output))
(eval-when (:load-toplevel)
  (print '(:load :d))
  (finish-output))
(eval-when (:execute)
  (print '(:execute :d))
  (finish-output))
