(eval-when (:compile-toplevel)
  (print '(:compile :e))
  (finish-output))
(eval-when (:load-toplevel)
  (print '(:load :e))
  (finish-output))
(eval-when (:execute)
  (print '(:execute :e))
  (finish-output))
